# Perfil full — todo instalado

[workflows]
webdev=1
gamedev=1
audio=1

[system]
login_method=startx
zram_size=ram/2
zram_swappiness=180
aur_helper=auto
change_shell=1
browser=chromium

[desktop]
enable_picom=1
enable_polybar=1
fastfetch_on_terminal=1
zellij_autostart=1
