# Perfil minimal — solo escritorio base, sin workflows pesados

[workflows]
webdev=0
gamedev=0
audio=0

[system]
login_method=startx
zram_size=ram/2
zram_swappiness=180
aur_helper=auto
change_shell=1
browser=chromium

[desktop]
enable_picom=1
enable_polybar=1
fastfetch_on_terminal=1
zellij_autostart=0
